steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/minimal-app:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/minimal-app:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', |
      if [ "$BRANCH_NAME" == "develop" ]; then
        gcloud run deploy dev-service --image gcr.io/$PROJECT_ID/minimal-app:$SHORT_SHA --region YOUR_REGION --platform managed --update-env-vars ENV=dev,HOST=0.0.0.0,PORT=8080;
      elif [ "$BRANCH_NAME" == "main" ]; then
        gcloud run deploy stag-service --image gcr.io/$PROJECT_ID/minimal-app:$SHORT_SHA --region YOUR_REGION --platform managed --update-env-vars ENV=stag,HOST=0.0.0.0,PORT=8080;
      elif [[ "$TAG_NAME" == v* ]]; then
        gcloud run deploy prod-service --image gcr.io/$PROJECT_ID/minimal-app:$SHORT_SHA --region YOUR_REGION --platform managed --update-env-vars ENV=prod,HOST=0.0.0.0,PORT=8080;
      fi
    ]
images:
  - 'gcr.io/$PROJECT_ID/minimal-app:$SHORT_SHA'
