steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/minimal-app:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/minimal-app:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "$BRANCH_NAME" == "develop" ]; then
          gcloud run deploy minimal-app-dev --image gcr.io/$PROJECT_ID/minimal-app:$SHORT_SHA --region $_DEPLOY_REGION --platform managed --update-env-vars ENV=dev,HOST=0.0.0.0;
        elif [ "$BRANCH_NAME" == "main" ]; then
          gcloud run deploy minimal-app-stag --image gcr.io/$PROJECT_ID/minimal-app:$SHORT_SHA --region $_DEPLOY_REGION --platform managed --update-env-vars ENV=stag,HOST=0.0.0.0;
        elif [[ "$TAG_NAME" == v* ]]; then
          gcloud run deploy minimal-app-prod --image gcr.io/$PROJECT_ID/minimal-app:$SHORT_SHA --region $_DEPLOY_REGION --platform managed --update-env-vars ENV=prod,HOST=0.0.0.0;
        fi
images:
  - 'gcr.io/$PROJECT_ID/minimal-app:$SHORT_SHA'
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
serviceAccount: "50348277979-compute@developer.gserviceaccount.com"